### ISSUE TITLE
Map Local does not work when using Atlantis on device

### ISSUE THREAD

**Issue by johanthorell** [ProxymanApp/atlantis#62]
Hi!

I’m using Atlantis and everything seems to setup correctly, I can see all the traffic from the device etc, but when I try to map a response nothing happens. In this example a replaced the status code but when I re run the app nothing gets mapped. Same map local works as expected in the simulator.
<img width="1680" alt="Screenshot 2021-04-05 at 15 09 55" src="https://user-images.githubusercontent.com/55987769/113577802-1b89c400-9622-11eb-9cdb-4c334a71b9c0.png">

**Comment by NghiaTranUIT** [comment]
Hi @johanthorell, when you're using Atlantis, you couldn't use any Debugging tools, like Map Local, Breakpoint, etc because Atlantis is not built for debugging.

To use Map Local, Please install the certificate on your iOS Devices (Certificate Menu -> Install Certificate for iOS -> Physical Devices), then you can use Map Local as you wish 👍

**Comment by NghiaTranUIT** [comment]
Atlantis is for quick preview the Traffic from your app, it's not for debugging 😄

**Comment by johanthorell** [comment]
Oh ok, thanks for the info and the super fast reply!
